version: '3.8'

services:
  buscador-sopa-letras:
    build: .
    ports:
      - "80:80"
      - "5000:5000"
    container_name: buscador-sopa-letras
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 